# Generated by Django 5.2.2 on 2025-06-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='amount_in_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
