# Generated by Django 5.2.2 on 2025-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_amount_in_stock_alter_material_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
