# Generated by Django 5.2.2 on 2025-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
