# Generated by Django 5.2.2 on 2025-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialcategory_remove_materialrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
